### ISSUE TITLE
Control clicking on links works badly

### ISSUE THREAD

**Issue by bjorn3** [DioxusLabs/docsite#11]
If I control click on any menu item to open it in a new page it changes the current page to the intended page without changing the url and opens the previous page in a new tab.

1. Go to https://dioxuslabs.com/blog/introducing-dioxus

![image](https://user-images.githubusercontent.com/17426603/148091552-708357a9-1d3d-4db5-a68d-2250cc4c4843.png)

2. control click on "home"

3. original tab becomes the blog page without changing the url

![image](https://user-images.githubusercontent.com/17426603/148091678-f52cf8da-9398-4f93-9a63-d2e796bf4fdb.png)

4. the new tab points to the original page

![image](https://user-images.githubusercontent.com/17426603/148091736-cc282bd4-e209-470b-82f6-18f82c5a05f3.png)

**Comment by jkelleyrtp** [comment]
I've updated the router to not be as terrible.

Can you check if this issue still persists?

**Comment by bjorn3** [comment]
It now doesn't open a new tab at all anymore. The url and shown page get updated like it should for a click without control. Right click and then open in new tab works as it should and so does middle mouse button click. It is just control click that is now broken.
