### ISSUE TITLE
|| in code blocks shown as | in firefox

### ISSUE THREAD

**Issue by bjorn3** [DioxusLabs/docsite#12]
![image](https://user-images.githubusercontent.com/17426603/148091857-e9bd4063-c03d-4623-894d-7a0a89c88ca7.png)

The first `|` is visible in the dev tools, but doesn't render anything.

**Comment by jkelleyrtp** [comment]
We use https://prismjs.com to render code.

Does the same issue occur for you on Prism's website?

**Comment by bjorn3** [comment]
No

![image](https://user-images.githubusercontent.com/17426603/148210817-0dcf0c54-64e6-4d41-8104-ba590adb6227.png)

**Comment by jkelleyrtp** [comment]
I've tried to replicate this in FF 95.0.2 (64-bit) but can't. Perhaps a style is conflicting?

<img width="978" alt="Screen Shot 2022-01-05 at 3 35 15 PM" src="https://user-images.githubusercontent.com/10237910/148285498-5e26aa89-c803-4171-a427-00c88b1438ff.png">

**Comment by bjorn3** [comment]
This is still an issue. I am using firefox developer edition 96.0b10 (64-bit) by the way.

**Comment by jkelleyrtp** [comment]
I downloaded FF 96.0b10 (64-bit) (macOS, M1) and still don't get the rendering bug.

I'm using an entirely fresh install with no plugins/extensions/darkmode enabled.


<img width="964" alt="Screen Shot 2022-01-06 at 9 50 53 AM" src="https://user-images.githubusercontent.com/10237910/148401514-7ccb2274-c02a-405a-9ba3-186d5dc54def.png">

**Comment by bjorn3** [comment]
Could it be that firefox uses a different font renderer on macOS versus Linux. Or maybe the following in the console is related?

```
Navigated to https://dioxuslabs.com/blog/introducing-dioxus/
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
introducing-dioxus
GEThttps://dioxuslabs.com/blog/introducing-dioxus/src/darktheme.js
[HTTP/2 404 Not Found 24ms]

GEThttps://dioxuslabs.com/blog/introducing-dioxus/src/components/prism/prism.js
[HTTP/2 404 Not Found 24ms]

GEThttps://dioxuslabs.com/blog/introducing-dioxus/tailwind.css
[HTTP/2 404 Not Found 11ms]

Loading failed for the <script> with source “https://dioxuslabs.com/blog/introducing-dioxus/src/darktheme.js”. introducing-dioxus:32:1
Loading failed for the <script> with source “https://dioxuslabs.com/blog/introducing-dioxus/src/components/prism/prism.js”. introducing-dioxus:33:1
GEThttps://dioxuslabs.com/favicon.ico
[HTTP/2 404 Not Found 8ms]

Uncaught ReferenceError: Prism is not defined
    <anonymous> https://dioxuslabs.com/blog/introducing-dioxus/ line 1099 > injectedScript:1
    __wbg_appendChild_d318db34c4559916 https://dioxuslabs.com/index-ab1fef4e881bbb3b.js:1099
    handleError https://dioxuslabs.com/index-ab1fef4e881bbb3b.js:285
    __wbg_appendChild_d318db34c4559916 https://dioxuslabs.com/index-ab1fef4e881bbb3b.js:1098
    __wbg_adapter_46 https://dioxuslabs.com/index-ab1fef4e881bbb3b.js:267
    real https://dioxuslabs.com/index-ab1fef4e881bbb3b.js:199
    promise callback*init/imports.wbg.__wbg_then_2fcac196782070cc https://dioxuslabs.com/index-ab1fef4e881bbb3b.js:1059
    init https://dioxuslabs.com/index-ab1fef4e881bbb3b.js:1133
    async* https://dioxuslabs.com/blog/introducing-dioxus/:36
line 1099 > injectedScript:1:1
```

**Comment by azzamsa** [comment]
I can confirm this.

Brave:

![image](https://user-images.githubusercontent.com/17734314/164548398-8e1e2518-6009-4ae2-beba-66b852a5e31d.png)

Firefox 99.0.1:

![image](https://user-images.githubusercontent.com/17734314/164548513-bea30741-cb8a-4f3c-bc4d-249234f13b29.png)

![image](https://user-images.githubusercontent.com/17734314/164548574-684c3aeb-aca1-4429-b3b6-52add4c10e5c.png)
