### ISSUE TITLE
Line breaks in Markdown don't count as a space

### ISSUE THREAD

**Issue by tigerros** [DioxusLabs/docsite#126]
In "normal" Markdown, a single line break displays a space. Example:
```
... this line is very long and hard to edit in an editor,
so here's a line break!
```
displays: `... this line is very long and hard to edit in an editor, so here's a line break!`. This is not the case on the docsite, so there's awkward missing spaces. For example, in [cookbook/examples](https://dioxuslabs.com/learn/0.4/cookbook/examples), there's this:
```
... or you just want to see cool thingsthat you can do with Dioxus, make sure to give these a look!
                                 ^^^^^^^^^^
```
Equivalent Markdown:
```
... or you just want to see cool things
that you can do with Dioxus, make sure to give these a look!
```

**Comment by tigerros** [comment]
This might actually belong in [DioxusLabs/include_mdbook](https://github.com/DioxusLabs/include_mdbook)

**Comment by ealmloff** [comment]
This is a bug with https://github.com/DioxusLabs/include_mdbook. That crate handles converting markdown to rsx ([text is converted here](https://github.com/DioxusLabs/include_mdbook/blob/main/mdbook-macro/src/rsx.rs#L74)). We should track if the last node was a text node and insert a space if we find two adjacent text nodes

**Comment by tigerros** [comment]
I'm trying to implement it but don't know how to get the Markdown value to test it :( It only shows chapters/sections/etc. but not the actual content. Tried `&*LAZY_BOOK.get_page(PageId { 0: 0 }).sections.first().unwrap()`, but that doesn't have the content either.

**Comment by tigerros** [comment]
Moved to https://github.com/DioxusLabs/include_mdbook/issues/3
