### ISSUE TITLE
Diplex global state managment library doesn't seem to exist

### ISSUE THREAD

**Issue by colepoirier** [DioxusLabs/docsite#14]
The Diplex global state management library mentioned here <https://github.com/DioxusLabs/docsite/blob/b92993ebca89ea954d44f608d36a24fefc4531eb/snippets/mod.rs#L116> doesn't show up in github searches of this organization or 'all of github' and doesn't show up on google either. Did the name of this library change? Is the library private? Thanks for your clarifications!

**Comment by jkelleyrtp** [comment]
Hey! I changed the name and rewrote the library a few times.

Write now it's "fermi". Unfortunately it really lacks documentation but you might be able to figure out how to use it.


https://github.com/DioxusLabs/fermi/tree/master/src

**Comment by colepoirier** [comment]
Thanks for your swift reply! Great to see you are reworking the library to make it even better. Do you plan on updating the above reference and any other dangling ones so it points to the new iteration of diplex which is fermi?

**Comment by colepoirier** [comment]
Fermi has since been moved into the main dioxus repo here https://github.com/DioxusLabs/dioxus/tree/master/packages/fermi.
