### ISSUE TITLE
Use App instead of app in all getting started guides

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/docsite#168]
We should use App in all of the getting started platform guides to be more consistent with the hackernews guide. Some of the guides already use App, but some like the [fullstack guide](https://dioxuslabs.com/learn/0.4/getting_started/fullstack) do not

**Comment by neonwuchang** [comment]
1. Does this refer only to occurrences of fn app( ) ?
2. Should the updation be limited to code examples used in the getting started part only?

**Comment by ealmloff** [comment]
> 1. Does this refer only to occurrences of fn app( ) ?
> 2. Should the updation be limited to code examples used in the getting started part only?

It would be nice if it was consistent across all the docs, but this issue is specifically about the platform getting started guides because the code you create in those guides can be used to start the hackernews guide.
