### ISSUE TITLE
Version 0.4 Router Example Project page still links to the 0.3 Dioxus Book

### ISSUE THREAD

**Issue by wzwywx** [DioxusLabs/docsite#174]
In version 0.4 of the reference, the Router Example Project section (specifically the Overview [page](https://dioxuslabs.com/learn/0.4/router/example)) which suggests reading the book before going further, still points to the 0.3 book.

> To follow along with the router example, you'll need a working Dioxus app.Check out the [Dioxus book](https://dioxuslabs.com/docs/0.3/guide/en/) to get started.

Maybe it should link to the 0.4 [Getting Started](https://dioxuslabs.com/learn/0.4/getting_started) page instead?

I can work on this if that's necessary.

**Comment by ealmloff** [comment]
Linking to the getting started page instead would be great!
