### ISSUE TITLE
Code formatting error in docs

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [DioxusLabs/docsite#18]
See https://dioxuslabs.com/guide/setup.html

jump down to linux specifics part...

looks like you switched from <code></code> markup to ``` markdown half way through that doc....

Didn't have time to do a PR - sorry

**Comment by azzamsa** [comment]
Would you like to point out?

![image](https://user-images.githubusercontent.com/17734314/164428751-2ffaa2ff-825f-4421-936a-363596a818e2.png)

**Comment by andrewdavidmackenzie** [comment]
Must have been fixed as I don't see it any more (sorry, should have added screen shot with issue...)
