### ISSUE TITLE
Is there a reason Tide’s contributing documents are linked in the README?

### ISSUE THREAD

**Issue by wzwywx** [DioxusLabs/docsite#182]
I thought Tide was something related to Dioxus but it doesn’t seem to be. And I think Dioxus has its own contributing guideline so that makes it even odder to link to Tide’s docs.

Perhaps I missed something obvious here.

**Comment by ealmloff** [comment]
Good catch! No, Dioxus is not related to tide. That might have been left over from copying a template? https://github.com/DioxusLabs/dioxus/commit/1880bdb308c15233a78cf313190ec41254137b93 removes that link

**Comment by wzwywx** [comment]
Ah, noted. Thank you for clarifying that.
