### ISSUE TITLE
Rendering issue on mobile

### ISSUE THREAD

**Issue by ctjhoa** [DioxusLabs/docsite#19]
**To Reproduce**

-  Go to https://dioxuslabs.com/
-  Open dev tools and switch to mobile view (eg. iphone 11 size)
    Scroll to the right

![Screenshot_20220208-224305.png](https://user-images.githubusercontent.com/1716173/153080982-1a34c80f-1a78-4a0a-a318-d617b925e8c8.png)

**Environment**
- Browser: Firefox 94.0

**Comment by jkelleyrtp** [comment]
Just pushed a fix - can you see if this still impacts you?

**Comment by ctjhoa** [comment]
That's fixed, thanks!
