### ISSUE TITLE
Docs for creating a UI library

### ISSUE THREAD

**Issue by itsezc** [DioxusLabs/docsite#196]
A lot of web apps and companies are opting to creating design systems, and UI library goes hand in hand with these. There's many UI libraries out there for other frameworks like React and Svelte, it'd be great if we can put together on the best way to put a simple UI library for Dioxus together along with the best practices for how to set one up.

**Comment by ealmloff** [comment]
I think this is too specific to justify maintaining documentation in the docsite. If anyone is interested in creating a UI library, discussions or the discord are good places to discuss best practices.

Some previous discussions:

- https://github.com/DioxusLabs/dioxus/issues/1483
- https://github.com/DioxusLabs/dioxus/discussions/1114
