### ISSUE TITLE
Wrong instructions for installing dioxus cli on Tailwind doc page

### ISSUE THREAD

**Issue by ochrons** [DioxusLabs/docsite#208]
Location: https://dioxuslabs.com/learn/0.4/cookbook/tailwind

Currently it says to use

```
cargo install --git https://github.com/DioxusLabs/cli
```

but this doesn't work anymore. Correct installation command is
```
cargo install dioxus-cli
```
which is also used elsewhere in the documentation.

Alternatively this step could be just omitted, as it can be assumed that users have already installed dioxus-cli by the time they start using Tailwind in their projects.

**Comment by ealmloff** [comment]
closed by #217
