### ISSUE TITLE
Hooks documentation has redundant sections

### ISSUE THREAD

**Issue by thorn132** [DioxusLabs/docsite#212]
The Hooks page contains two sections for `use_signal` since it replaced both `use_state` and `use_ref` in 3c6517e. The second section currently includes:
> use_signal is great for tracking simple values. However, in the Signal API, you may notice that the only way to modify its value is to replace it with something else

> Thankfully, there is another hook for that, use_signal! It is similar to use_signal, but it lets you get a mutable reference to the contained data.

The redundant sections need to be merged, and any other outdated information removed.

**Comment by ealmloff** [comment]
Fixed in https://github.com/DioxusLabs/docsite/pull/219
