### ISSUE TITLE
Small issues in 0.5.0 docs

### ISSUE THREAD

**Issue by ochrons** [DioxusLabs/docsite#213]
1. the 0.5.0 docs should explicitly tell users to install the 0.5.0 version of CLI `cargo install dioxus-cli@0.5.0-alpha.0` since the older CLI versions are not fully compatible (https://dioxuslabs.com/learn/0.5/getting_started/wasm)
2. Dioxus CLI readme should also have installation instructions for 0.5.0
3. pointing users to a very old blog post (https://dioxuslabs.com/blog/introducing-dioxus) on the [first intro](https://dioxuslabs.com/learn/0.5/) page might not be the best idea
4. examples for Liveview https://dioxuslabs.com/learn/0.5/getting_started/liveview for Salvo and Warp do not exist anymore. I suppose these should also be dropped from https://dioxuslabs.com/learn/0.5/getting_started/fullstack
5. CodeSandbox is out of credits, for example on https://dioxuslabs.com/learn/0.5/reference/fullstack/server_functions
6. In https://dioxuslabs.com/learn/0.5/reference/use_resource the dependencies example doesn't actually provide a tuple of dependencies. Is it even possible with `use_resource`?
7. In the same page the first example could be simplified to
```rust
    let mut future = use_resource( || async {
        reqwest::get("https://dog.ceo/api/breeds/image/random")
            .await
            .unwrap()
            .json::<String>()
    });
```
8. On the same page it says `We can use .value() to get the result of the future.` but the example uses `read()`. Calling it as `future` is misleading as it's a `Resource<impl Future>`
9. On the same page it says `The UseFuture handle provides a restart method` but this a `Resource` now
10. In https://dioxuslabs.com/learn/0.5/guide/data_fetching there should be an instruction on adding `reqwest` and `serde` crates
11. Example on https://dioxuslabs.com/learn/0.5/reference/fullstack/server_functions could be simplified as
```rust
let count = use_server_future(get_server_data)?;
```
The returned value is `Some(Ok("Hello from the server!"))` instead of `Ok("Hello from the server!")`

**Comment by LouisTruch** [comment]
There is also a little typo [there]( https://dioxuslabs.com/learn/0.5/cookbook/tailwind#setup), in the snippet for installing Manganis `cargo add maganis` "maganis" instead of "manganis"
