### ISSUE TITLE
Go to version "0.4" points to learn/0.5

### ISSUE THREAD

**Issue by mrguiman** [DioxusLabs/docsite#230]
Currently, the `0.4` entry in the `Go to Version` section of the website points to 0.5.

I've tracked it down to this line and commit: https://github.com/DioxusLabs/docsite/commit/a1d7f686e733408d6129eaafb09ddf7d0673dcbd#diff-6f2621f79823a7cbd21c980e1345c07f261654e65e90eac365551963dd5bbe7dR76

Although the issue could be more involved, I'm lacking the background knowledge though

**Comment by ealmloff** [comment]
Oops, that link should not have been updated with the 0.5 release. Fixed by https://github.com/DioxusLabs/docsite/commit/3d3292db73766d690d9023ea759f9b6a43052e19
