### ISSUE TITLE
Document dependency for Linux installation

### ISSUE THREAD

**Issue by MassiminoilTrace** [DioxusLabs/docsite#235]
While trying to run an example Dioxus 0.5 project with the latest dx tool, targeting dioxus_desktop, I had a linking error.
I got the same error both on Debian12 and Ubuntu 22.04, on different computers.

I installed all the suggested Tauri dependencies, but the error still appears.
`ld` complains about a missing `xdo` library.

Installing the package `libxdo-dev` fixes the problem :)

**Comment by neupsh** [comment]
For archlinux:

```
sudo pacman -S xdotool 
```

**Comment by ealmloff** [comment]
Closed by #267
