### ISSUE TITLE
Missing spaces in router guide

### ISSUE THREAD

**Issue by elias098** [DioxusLabs/docsite#243]
There are missing spaces throughout the whole router guide.
I am using chrome on macOS if it is relevant.

images are from https://dioxuslabs.com/learn/0.5/router/example/redirection-perfection
![image](https://github.com/DioxusLabs/docsite/assets/28680066/e4548aa3-d803-4eef-aee4-9e2a2536c168)
![image](https://github.com/DioxusLabs/docsite/assets/28680066/d45b25ba-bb6f-424f-ba67-c21ca69fa02c)

**Comment by ealmloff** [comment]
This is caused by https://github.com/DioxusLabs/include_mdbook/issues/3
