### ISSUE TITLE
rsx reference - inconsistencies

### ISSUE THREAD

**Issue by frantisek-heca** [DioxusLabs/docsite#249]
1. div => button
<img width="814" alt="image" src="https://github.com/DioxusLabs/docsite/assets/25659432/61d46235-fe6a-43b3-86a7-ac920bdd5851">

----

2. confusing camelCase html attributes, they are mostly kebab-case
<img width="753" alt="image" src="https://github.com/DioxusLabs/docsite/assets/25659432/581e6f04-6489-4ecc-bc14-d469ad78ce4f">

----

3. there is no mention of the `color` above at the docs, at all
<img width="780" alt="image" src="https://github.com/DioxusLabs/docsite/assets/25659432/09019623-cf5c-470a-a159-09d61074ed30">

**Comment by ZephyrZhang3** [comment]
1. not empty & not div🤣
2. I think it means `img {}`, I think it's better to use comment mark like 1.
```
rsx! {
    img {    <-------
        // attributes
        width: "10px"  // name: value
    } <--------
}
```

**Comment by frantisek-heca** [comment]
Hmm.. I am sorry for not understanding the 2nd case. I have to delete it (cross it)...
Somehow I was expecting they talk about using `name` props in brackets... "http://{name}whatever` - my mistake.
