### ISSUE TITLE
Update dioxus logger documentation

### ISSUE THREAD

**Issue by ochrons** [DioxusLabs/docsite#260]
Later version of Dioxus logger switched to `tracing` instead of `log` in its dependencies. The documentation is not updated to reflect this change.

https://dioxuslabs.com/learn/0.5/cookbook/integrations/logging

**Comment by ochrons** [comment]
nvm, there's already a PR 😁
https://github.com/DioxusLabs/docsite/pull/259

**Comment by ealmloff** [comment]
Closed by https://github.com/DioxusLabs/docsite/pull/259
