### ISSUE TITLE
cargo install command in getting started guide returns invalid value error

### ISSUE THREAD

**Issue by ducc** [DioxusLabs/docsite#265]
Hello!

When running `cargo install dioxus-cli@0.5` from the [getting started guide](https://dioxuslabs.com/learn/0.5/getting_started) I receive the following error.

```
error: invalid value 'dioxus-cli@0.5' for '[CRATE[@<VER>]]...': unexpected end of input while parsing minor version number

  tip: if you want to specify SemVer range, add an explicit qualifier, like '^0.5'

For more information, try '--help'.
```

I believe this should be changed to `cargo install dioxus-cli@^0.5` :)

```
➜  cargo version
cargo 1.78.0-nightly (7bb7b5395 2024-01-20)
➜  rustc -V
rustc 1.78.0-nightly (b11fbfbf3 2024-02-03)
```

Thank you!

**Comment by ealmloff** [comment]
Thanks for letting us know. Fixed in https://github.com/DioxusLabs/docsite/commit/3c5bfca1dcea7f260dfe8f9a2a5fe46f53485c10
