### ISSUE TITLE
Desktop specific dependencies section has invisitble text

### ISSUE THREAD

**Issue by asmyers** [DioxusLabs/docsite#266]
The [Desktop specific dependencies](https://dioxuslabs.com/learn/0.5/getting_started) section appears to have white text on a white background.

<img width="754" alt="Screenshot 2024-04-27 at 5 17 22 PM" src="https://github.com/DioxusLabs/docsite/assets/122908/01c7c767-7c7d-47e3-ba23-914eb523272d">

**Comment by ealmloff** [comment]
Fixed in https://github.com/DioxusLabs/docsite/commit/10b7e5c17b52d189fc6ca8573dac6564449976c0
