### ISSUE TITLE
Code blocks are all black when highlighter JS does not run

### ISSUE THREAD

**Issue by mattfbacon** [DioxusLabs/docsite#303]
For progressive enhancement reasons it would be nice if the code was still visible without syntax highlighting in this case. Or better, do the highlighting in the SSG.

**Comment by ealmloff** [comment]
The code blocks in the docs and homepage are highlighted with inline styles during SSG, but the blog posts are converted from an external tool that requires other scripts

**Comment by mattfbacon** [comment]
Ok, then maybe we can change the css so the text is at least visible
