### ISSUE TITLE
CSS is broken

### ISSUE THREAD

**Issue by UE2020** [DioxusLabs/docsite#31]
The CSS is broken on the blog page. It works fine if you navigate to the home page and get to the blog from there.

Steps to reproduce:

1. Click here: https://dioxuslabs.com/blog/
2. See broken CSS

**Comment by Demonthos** [comment]
The entire folder of https://github.com/DioxusLabs/docsite/tree/gh-pages/docs/blog is handcompiled. Could we change the CI to copy the main index.html to the blog index.html?
```
cp docs/index.html docs/blog/index.html
```
