### ISSUE TITLE
0.5 docs use 0.6 code examples

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/docsite#319]
There are breaking changes between dioxus 0.5 and dioxus 0.6. The 0.5 docs were updated to use the examples that compile with 0.6 which means those examples no longer compile. A few examples:

- The path to eval has changed which breaks https://dioxuslabs.com/learn/0.5/reference/web#running-javascript
![Screenshot 2024-11-07 at 7 56 08 AM](https://github.com/user-attachments/assets/761a5439-ec67-4a86-9a0b-6da8fbf60b4e)

- The paths that `asset!` accept have changed which breaks the tailwind guide
![Screenshot 2024-11-07 at 7 57 56 AM](https://github.com/user-attachments/assets/f02279d8-a335-48c9-9ba8-dce763d05252)

**Comment by jkelleyrtp** [comment]
Fixed in https://github.com/DioxusLabs/docsite/commit/2c78347cae593d829f14a731e439c315fb3c00d4
