### ISSUE TITLE
Consider reversing the order of the Release Notes on the front page

### ISSUE THREAD

**Issue by philpax** [DioxusLabs/docsite#32]
Hiya! Was looking at the Dioxus website, as one does, and noticed this:
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/707827/174488922-a3f080b4-f7ce-42de-b124-62aaa7581008.png">
I'd normally expect the more recent post to be first, and this might lead to people glancing over the rest of the list and ignoring newer posts.

I'd submit a PR for this, but I don't want to step on any toes 🙏

**Comment by jkelleyrtp** [comment]
Fixed in the most recent push!
