### ISSUE TITLE
Many links now 404

### ISSUE THREAD

**Issue by nicoburns** [DioxusLabs/docsite#329]
A large number of links in the docsite link to non-existent pages. For example, most of the examples on https://dioxuslabs.com/learn/0.6/cookbook/examples/.

These should be cleaned up. But perhaps we should also implement some kind of automated checker for this, that can notify when links disappear?

**Comment by DogeDark** [comment]
We have a link checker CI in the main Dioxus repo that could be added here and scheduled to run every few days.

**Comment by johnny-smitherson** [comment]
Happens also on all these links under reference:   https://dioxuslabs.com/learn/0.5/reference/



>>> [RSX](https://dioxuslabs.com/learn/0.5/reference/reference/rsx) Rsx is a HTML-like macro that allows you to declare UI
>>> [Components](https://dioxuslabs.com/learn/0.5/reference/reference/components) Components are the building blocks of UI in Dioxus
>>> [Props](https://dioxuslabs.com/learn/0.5/reference/reference/component_props) Props allow you pass information to Components
>>> [Event Listeners](https://dioxuslabs.com/learn/0.5/reference/reference/event_handlers) Event listeners let you respond to user input
>>> [User Input](https://dioxuslabs.com/learn/0.5/reference/reference/user_input) How to handle User input in Dioxus
>>> [Dynamic Rendering](https://dioxuslabs.com/learn/0.5/reference/reference/dynamic_rendering) How to dynamically render data in Dioxus


Note how all the links I copy pasted above have `.../reference/reference/...` 

They all return 404 and render home page, user needs to fix link by hand every page in the reference

**Comment by jkelleyrtp** [comment]
Figured this out - our include_mdbook crate was generating the wrong urls.

We were getting this problem wrong: https://stackoverflow.com/questions/5457885/relative-urls-and-trailing-slashes

I also just dropped the examples pages since they were full of crates that we don't support anymore.
