### ISSUE TITLE
doesn't build

### ISSUE THREAD

**Issue by adsick** [DioxusLabs/docsite#35]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/24528839/176225833-cb24cf1a-606c-4d10-a993-a931188b5dbf.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/24528839/176225878-f626e44d-e369-438e-8936-d1d8826f3c84.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/24528839/176225896-fcde238c-4d4e-4b3d-aaa0-3a1aaf294e9a.png">

what I've run: 
`gh repo clone DioxusLabs/docsite`
`trunk serve`

```
▶ rustup -V
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.61.0 (fe5b13d68 2022-05-18)`
```

**Comment by Demonthos** [comment]
It looks like escape sequences are broken on master. Once that is fixed this should be resolved.
