### ISSUE TITLE
"Getting Started: Web" guide suggestions wrong cargo add command

### ISSUE THREAD

**Issue by Cldfire** [DioxusLabs/docsite#52]
https://dioxuslabs.com/reference/platforms/web says:

> Add Dioxus with the web features:
>
> ```
> $ cargo add dioxus --features web
> ```

However `cargo add dioxus --features web` results in:

```
cldfire@jarekspsonalmbp project % cargo add dioxus --features web
    Updating crates.io index
      Adding dioxus v0.3.1 to dependencies.
error: unrecognized feature for crate dioxus: web
enabled features:
    dioxus-core-macro, dioxus-hooks, dioxus-html, dioxus-rsx, hooks, html, macro
```

Seems to me the default features are set up for a web build as of today.

**Comment by Cldfire** [comment]
Also the suggested `main.rs` starter code is broken as well; looks like the "Getting Started: Web" guide just needs to be updated in general.

**Comment by marc2332** [comment]
hey! It was updated to the latest v0.3 changes  https://dioxuslabs.com/docs/0.3/guide/en/getting_started/web.html
