### ISSUE TITLE
Terminal UI widgets example link broken

### ISSUE THREAD

**Issue by mcginty** [DioxusLabs/docsite#64]
Page: https://dioxuslabs.com/docs/0.3/guide/en/getting_started/tui.html

The site says "See the [widgets example](https://github.com/DioxusLabs/dioxus/blob/master/packages/tui/examples/widgets.rs)", which leads to a `tui` package, when it's now `dioxus-tui`.

**Comment by Demonthos** [comment]
This is already fixed in the nightly version of the docs: https://dioxuslabs.com/docs/nightly/guide/en/getting_started/tui.html
