### ISSUE TITLE
Links to examples broken

### ISSUE THREAD

**Issue by matt-izatt** [DioxusLabs/docsite#8]
The links to the examples under the heading **Feature-packed examples** on the home page lead to a 404 page on GitHub.

It looks like the examples have been moved to their own repo. E.g. link says https://github.com/dioxuslabs/todomvc instead of https://github.com/dioxuslabs/example-projects/tree/master/todomvc

**Comment by jkelleyrtp** [comment]
Ah yep, I consolidated all the examples but broke the links. Will fix it! Thanks!

**Comment by matt-izatt** [comment]
Oops sorry just saw this. You can close my PR :)
