### ISSUE TITLE
Sidebar overlaps with main content

### ISSUE THREAD

**Issue by eventualbuddha** [DioxusLabs/docsite#87]
At some viewport sizes the sidebar overlaps with the main content:

<img width="347" alt="image" src="https://github.com/DioxusLabs/docsite/assets/1938/b6a24ca2-641e-41b2-a27c-628df6bd8d06">

This was in Arc (Chrome, effectively) with a `clientWidth` of 1232 on this page: https://dioxuslabs.com/learn/0.4/getting_started/fullstack.

**Comment by ianpurton** [comment]
I came here to say the same thing

![image](https://github.com/DioxusLabs/docsite/assets/36966/23937d21-ffd9-4c03-8e63-c3bd1f5b47fa)
