### ISSUE TITLE
Setup guides links point to 404

### ISSUE THREAD

**Issue by MassiminoilTrace** [DioxusLabs/docsite#99]
- Navigate to the "setup guides" section https://dioxuslabs.com/learn/0.4/getting_started/#setup-guides
- Click one of the links of the list
- You are redirected to a 404 page

It seems the links are incorrectly generated, with an additional "getting_started" in between. For example, the "Desktop" link points to `/learn/0.4/getting_started/getting_started/desktop` instead of `/learn/0.4/getting_started/desktop`

**Comment by marc2332** [comment]
I can't reproduce this, maybe it got fixed since you opened this issue, are you still able to reproduce it?

**Comment by MassiminoilTrace** [comment]
I guess you're right, I deleted Firefox's cache and it seems to work now.

Still strange tho, those URLs in the HTML are relative urls like `getting_started/desktop`; maybe the browser concatenated that relative url to the current page and doubled a part of the url as a result. All the other ones are absolute urls like `/learn/0.4/path...`.

Anyway it seems to work, I close the issue
thank you and sorry for the pretty useless bug report :/

**Comment by marc2332** [comment]
hey Massimo , don't worry 😄.  If you ever see something bugged or something weird, whatever, please open an issue, even if you are not completely sure about it 👍  Thanks !
